// Command export-card-metadata writes web/card-metadata.gen.js from gameplay.InitialCardCatalog().
// The UI loads English name, description, example, stats, type, and order from this file; only
// Portuguese lives in web/cards-catalog.js (PT object).
//
// Run from repo root after changing internal/gameplay/cards.go:
//
//	go run ./cmd/export-card-metadata
//
// Or: go generate ./internal/gameplay
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"power-chess/internal/gameplay"
)

type metadataRow struct {
	ID             string `json:"id"`
	Type           string `json:"type"`
	Mana           int    `json:"mana"`
	Ignition       int    `json:"ignition"`
	Cooldown       int    `json:"cooldown"`
	Targets        int    `json:"targets"`
	EffectDuration int    `json:"effectDuration"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	Example        string `json:"example"`
}

func main() {
	outPath := "web/card-metadata.gen.js"
	for i := 1; i < len(os.Args)-1; i++ {
		if os.Args[i] == "-out" {
			outPath = os.Args[i+1]
			break
		}
	}

	cat := gameplay.InitialCardCatalog()
	rows := make([]metadataRow, len(cat))
	for i, c := range cat {
		rows[i] = metadataRow{
			ID:             string(c.ID),
			Type:           strings.ToLower(string(c.Type)),
			Mana:           c.Cost,
			Ignition:       c.Ignition,
			Cooldown:       c.Cooldown,
			Targets:        c.Targets,
			EffectDuration: c.EffectDuration,
			Name:           c.Name,
			Description:    c.Description,
			Example:        c.Example,
		}
	}

	jsonBytes, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "export-card-metadata: %v\n", err)
		os.Exit(1)
	}

	js := fmt.Sprintf(`// Code generated by go run ./cmd/export-card-metadata. DO NOT EDIT.

globalThis.__POWER_CHESS_CARD_METADATA__ = %s;
`, string(jsonBytes))

	if err := os.WriteFile(outPath, []byte(js), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "export-card-metadata: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "export-card-metadata: wrote %s (%d cards)\n", outPath, len(rows))
}
